[package]
name = "pose_server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = ["bevy_sprite"] }
flatbuffers = "25.2.10"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
