@startuml

interface LandmarkStream
class RecordedStream
class LiveStream
class Character
class LandmarkFrame
class Routine
class Scoring
class Asset

LandmarkStream <|-- RecordedStream
LandmarkStream <|-- LiveStream

Routine ..> Character : uses
Routine ..> Scoring : creates
Routine ..> LiveStream : creates
Routine ..> RecordedStream : creates
Routine ..> Asset : uses


Character ..> LandmarkStream : uses
Character ..> LandmarkFrame : receives

LandmarkStream ..> LandmarkFrame : sends
Scoring ..> LandmarkStream : compares


@enduml
